version: '3'

services:
  staging-events-v2:
    build: .
    container_name: staging-reg-events-v2
    working_dir: /var/www/html
    ports:
      - 2020:80
    volumes:
      - .:/var/www/html
      - /tmp:/tmp

    user: ${CURRENT_UID}

    environment:
      APP_ENV: ${APP_ENV}  # Example environment variable
      APP_DEBUG: 'true'
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - staging-reg-events-v2
    depends_on:
      - db-events-stage-v2
    healthcheck:
      test: ["CMD", "curl", "-f", "https://events.ictc.go.tz"]
      interval: 30s
      timeout: 10s
      retries: 3

  db-events-stage-v2:
    image: mariadb:10.6.18
    container_name: ${DB_HOST}
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 1702:${DB_PORT}
    networks:
      - staging-reg-events-v2
    volumes:
      - mariadbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$DB_USERNAME --password=$DB_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3


  adminer:
    image: adminer
    restart: always
    networks:
      - staging-reg-events-v2
    ports:
      - 8081:8080

volumes:
  mariadbdata:
    driver: local

networks:
  staging-reg-events-v2:
    driver: bridge
