version: '3.1'

services:

  db:
    image: mariadb
    # restart: always
    environment:
      MARIADB_ROOT_PASSWORD: welcome
      MARIADB_DATABASE: ictc-ems
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql:Z

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
