version: '3.1'

services:

  db:
    image: mariadb
    # restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: welcome
      MARIADB_DATABASE: ictc-ems
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql:Z

  adminer:
    image: adminer
    # restart: unless-stopped
    ports:
      - 8080:8080

  mailpit:
    image: axllent/mailpit
    # restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db-data:
